@Host = http://localhost:10000
@userId = f6feffa8-e57e-4f5b-903e-6aabe26efc50

GET {{Host}}/users
Accept: application/json

###
GET {{Host}}/users/{{userId}}/comments
Accept: application/json

###
# Offset-based pagination
POST {{Host}}/users/{{userId}}/comments/offset
Accept: application/json
Content-Type: application/json

{
  "page": 10,
  "size": 100,
  "orderBy": "CREATED_AT",
  "direction": "DESC"
}

###

# Offset-based pagination
POST {{Host}}/comments/all
Accept: application/json
Content-Type: application/json

###

# Offset-based pagination
POST {{Host}}/comments/offset
Accept: application/json
Content-Type: application/json

{
  "page": 1,
  "size": 100,
  "skipCount": false,
  "orderBy": "CREATED_AT",
  "direction": "DESC"
}